openaddresses/machine

openaddr/cache.py

The 250 slice width was causing problems on some servers.

Use a smaller slice size for ESRI scraping

---

openaddr/conform.py

This is needed in order to be able to process archives with multiple files. In our [case](https://github.com/openaddresses/openaddresses/blob/master/sources/fi-uusimaa.json) the data is delivered together with a copy of the license and description of the data format.

Allow specifying filename for .csv-files

---

openaddr/conform.py

Something that would be super useful is appending postal/zip codes as a column in the CSV output. I started added support for it here.
Stil missing:
* Gracefully handling sources that doesn't have the `postcode` attribute
* Normalizing zip code (e.g. us-dc serves zip codes as a decimal number)
* Adding and supporting existing test cases
Unfortunately my python is very rusty, and I don't have a proper dev environment set up for machine right now. So any additional help with this PR would be much appreciated.

Added simple support for outputting postal codes in CSV

---

setup.py

Version 0.11.1 has a bug that breaks our Japanese sources;
it doesn't write non-ascii headers correctly. When that's
fixed it should be OK to update to latest again.
https://github.com/jdunck/python-unicodecsv/issues/54

Pin unicodecsv version to 0.11.0

---

chef/sources/recipes/default.rb
openaddr/run.py
openaddr/templates/user-data.sh
openaddr/tests/run.py
setup.py
test.py

Allowed connections to EC2 instance by specifying a key in `openaddr-ec2-run`, and pushing machine code up as a tarball.
Closes #108.

[WIP] Communicate directly with EC2

---

openaddr/conform.py

I didn't notice elaborate_filenames only converted to lowercase for shapefiles. This fixes the regression I introduced.
4 sources should be affected by this
```
au-queensland.json:        "file": "DP_PROP_LOCATION_INDEXQLD/WholeOfState_20140530.txt",
fi-uusimaa.json:        "file": "Paakaupunkiseudun_osoiteluettelo/PKS_avoin_osoiteluettelo.csv",
is.json:        "file": "STADFANG.dsv",
us-va.json:        "file": "VA_SiteAddress.txt",
```

Fix incorrect file selection for non-shapefiles

---

openaddr/conform.py

OK, here am I with another case sensitivity fix. :-)
Any postcode stored in a mixed case key isn't making it into the output because postcode was never added to the hardcoded list in conform_smash_case. Same thing for the keys to be added in #106.
I think it's safe to remove this hardcoded list and just lowercase everything except OA:x/OA:y as row_smash_case does. This will lowercase some extra keys like file and type but it looks like those aren't accessed after conform_smash_case is called anyway.

Remove hard-coded list of keys in conform_smash_case

---

chef/apache-worker/recipes/default.rb
chef/ec2-hostname/recipes/default.rb
chef/role-worker.json
openaddr/ci/__init__.py
openaddr/ci/run_dequeue.py
openaddr/ci/worker.py
openaddr/tests/ci.py
test.py

Setup for EC2 usage of openaddr workers, including URLs of output data and chef setup for public hostnames. Reports errors from `openaddr-process-one` and tracks source file IDs for future use in `runs` table.

Completed openaddr.ci.worker for EC2

---

openaddr/ci/__init__.py
openaddr/tests/ci.py

Uses a five-day time limit to prevent re-runs of identical sources.
Closes #133.

Reduce repeated runs

---

openaddr/ci/__init__.py
openaddr/ci/schema.pgsql
openaddr/tests/ci.py

Copy runs when reusing them, and ensure that status is handled correctly.
Added `status` boolean column to `runs` table.
Closes #137.

Re-use correct run status

---

openaddr/ci/__init__.py
openaddr/ci/schema.pgsql
openaddr/tests/ci.py

Track which runs are copies, and only use originals to determine repeats.
Closes #141.

Mark run copies

---

openaddr/ci/__init__.py
openaddr/ci/objects.py
openaddr/ci/webhooks.py
openaddr/tests/ci.py
test.py

This should make it easier to create a `Run` class and determine what DB indexes might be needed.
Closes #172.

Move DB queries down to ci.objects module

---

openaddr/conform.py
openaddr/tests/conform.py
openaddr/tests/conforms/lake-man-merge-postcode.json
openaddr/tests/sources/pl-dolnoslaskie.json
openaddr/tests/sources/us-ut.json

At the moment we have several internal machine functions whose output is forced upon the user.
The one I run into the most is the merge function. The user is forced to relate `merge: ['',''] => street: 'auto_street'`. 
This PR changes this behavior merging arrays automatically. 
so `{ merge: {'PRE','STR'}, street: 'auto_street'} `.  becomes `{ street: ['PRE','STR'] }`
cc/ @migurski (successor to #179 )

Add new merge behavior [WIP]

---

openaddr/conform.py
openaddr/tests/__init__.py
setup.py

* allows existing >2.6 installs of psycopg2 to work without trying to reinstall 2.6 (which fails on Windows w/o MSVS 2010)
* updated tests\__init__.py to work around fcntl only existing on Unix
* updated conform.py to add ".geojson" file extensions

Quickly update setup.py + conform.py

---

README.md
docs/README.md
docs/components.md
docs/persistence.md
docs/processes.md

@NelsonMinar, this is ready for your review.
Closes #203.

Document internals

---

openaddr/conform.py
openaddr/tests/__init__.py
openaddr/tests/conform.py
openaddr/tests/sources/us-ca-berkeley-apn.json

Recognizes an optional ID tag in the conform object, and outputs it as part of the processed CSV. Part of #163; this will be important for parcels later..

Recognize IDs

---

openaddr/__init__.py
openaddr/conform.py
openaddr/tests/__init__.py
openaddr/tests/conform.py
openaddr/tests/sources/pl-dolnoslaskie.json
openaddr/tests/sources/pl-lodzkie.json
openaddr/tests/sources/us-ca-alameda_county.json
openaddr/tests/sources/us-ca-berkeley.json
openaddr/tests/sources/us-ca-san_francisco.json
test.py

Supports new license dictionary behavior with two optional keys: `url` and `text`.
Closes #228, part of https://github.com/openaddresses/openaddresses-ops/issues/7.

Allow license dictionary

---

openaddr/__init__.py
openaddr/ci/webhooks.py
openaddr/conform.py
openaddr/process_one.py
openaddr/tests/__init__.py
openaddr/tests/ci.py
openaddr/tests/conform.py
openaddr/tests/sources/fr-paris.json
openaddr/tests/sources/fr/la-réunion.json

Adds input and output for required attribution flags on each run result, based on license and attribution source tags.
Closes #230, part of https://github.com/openaddresses/openaddresses-ops/issues/7.

Populate attribution

---

openaddr/conform.py

Completes the work from https://github.com/openaddresses/machine/pull/245, and might wrap up #244.
OGR doesn’t understand the `.txt` extension on its own, and needs to be told that these are CSV files.

Lying to OGR about .txt files

---

openaddr/__init__.py
openaddr/ci/webhooks.py
openaddr/conform.py
openaddr/process_one.py
openaddr/tests/__init__.py
openaddr/tests/ci.py
openaddr/tests/conform.py
openaddr/tests/sources/fr-paris.json
openaddr/tests/sources/fr/la-réunion.json
openaddr/tests/sources/pl-dolnoslaskie.json
openaddr/tests/sources/pl-lodzkie.json

Closes #253, part of https://github.com/openaddresses/openaddresses-ops/issues/7.

Populate share-alike

---

openaddr/__init__.py
openaddr/ci/__init__.py
openaddr/ci/collect.py
openaddr/ci/templates/index.html
openaddr/ci/templates/runs-table.html
openaddr/dotmap.py
openaddr/tests/__init__.py
openaddr/tests/ci.py
openaddr/tests/dotmap.py
openaddr/tests/util.py
openaddr/util/__init__.py
test.py

Splits collection files along share-alike-required flags from run state, and introduces `LocalProcessedResult` class instead of implicit tuple values. Display collection options on results page.
Closes #258, part of https://github.com/openaddresses/openaddresses-ops/issues/7.
Download page will look like this:

Separate share-alike collections

---

.travis.yml
openaddr/ci/worker.py
openaddr/tests/ci.py

Replaced default "user_input" name in worker with meaningful string

---

openaddr/__init__.py
openaddr/cache.py
openaddr/tests/cache.py

Give cacher knowledge of the conform object so it can request only the required fields

---

docs/components.md
openaddr/jobs.py

It's not unlimited, but let's try nine hours for now.
Closes #298.

Expand JOB_TIMEOUT to 9 hours

---

openaddr/conform.py

This was only a bug in Python2, not Python3.
See issue 310 for details.

Rewrite row number counting so it doesn't read the whole file into RAM

---

openaddr/ci/__init__.py
openaddr/ci/enqueue.py
openaddr/tests/ci.py

We want to sort the list of sources for a batch set, so that lengthy or unpredictable ones come first. This will reduce the long tail of workers enabling the the auto-scale pool to shrink in a more timely way. Follow-on to #298 related to potentially long-running mega sources.

Time-sort stream of sources for batch set

---

openaddr/ci/webapi.py
openaddr/tests/ci.py
setup.py

Supports https://github.com/openaddresses/openaddresses-ops/issues/11
Partial sample response:
{
"licenses": [
{
"attribution": null, "license": null,
"sources": [
["ca/bc/thompson-nicola-regional-district.json", "https://www.tnrd.ca/content/mapping-services-gis-overview"],
["ca/bc/vancouver.json", null]
]
},
{
"attribution": "ACT Government, Australia", "license": null,
"sources": [
["au/city_of_canberra.json", "http://www.actmapi.act.gov.au/html5.html"]
]
},
{
"attribution": null, "license": "Polish Law on Geodesy and Cartography of 17 May 1989 (https://github.com/openaddresses/openaddresses/issues/187#issuecomment-63327973)",
"sources": [
["pl/dolnoslaskie.json", null],
["pl/lodzkie.json", null]
]
},
{
"attribution": null, "license": "Public Domain",
"sources": [ …

Add dynamic license API response

---

openaddr/ci/collect.py
openaddr/tests/ci.py

Fix attribution language in downloads

---

openaddr/util/esri2geojson.py

Fixes #336 
I came across this when I tried to use `esri2geojson` without the new header and params flags. Adding the default empty lists prevents `_collect_headers()` and `_collect_headers()` from iterating over `None`.

Fix argparse arguments that append and are required.

---

openaddr/__init__.py
openaddr/ci/collect.py
openaddr/ci/objects.py
openaddr/tests/ci.py
openaddr/tests/dotmap.py

Found some straggling problems in collector process:
```
2016-06-29 05:00:06,964   ERROR: get() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/__init__.py", line 932, in decorated_function
return route_function(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/collect.py", line 90, in main
if test(result):
File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/collect.py", line 108, in <lambda>
return lambda result: (test1(result) and test2(result))
File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/collect.py", line 82, in <lambda>
'': (lambda result: result.run_state.get('share-alike', '') != 'true'),
TypeError: get() takes exactly 2 arguments (3 given)
```

Switched third arg of LocalProcessedResult to RunState

---

openaddr/ci/worker.py
openaddr/compat.py
openaddr/parcels/parse.py
openaddr/parcels/utils.py
openaddr/tests/ci.py

Try to collect output from more kinds of failed jobs.

Handle worker timeouts differently

---

chef/run.sh
circle.yml

PR #349 wants a newer version of GDAL that appears to be available on 14.04, so these changes are made in connection with a modification to build settings in Circle CI. It may be necessary to rebase PRs #333 and #351.

Upgrade CircleCI to use Ubuntu 14.04 (Trusty)

---

openaddr/ci/__init__.py
openaddr/ci/enqueue.py

It’s a bummer to tail the logs and not know how many sources remain.

Display remaining enqueued sources

---

openaddr/ci/collect.py
openaddr/tests/ci.py

Fixes #350
Uses multipart S3 upload inspired by [this post](http://codeinpython.blogspot.de/2015/08/s3-upload-large-files-to-amazon-using.html) and kinda copied from [this gist](https://gist.github.com/fabiant7t/924094).

Use multipart s3 upload

---

.gitignore
README.md

Installation seems to require a `dashboard` role so I've added that, as well as a couple of more trivial steps.
I've also added `.idea` to `.gitignore` as I often use PyCharm and I may not be the only one.

Expanding the installation prereqs.

---

chef/collector/recipes/default.rb
chef/role-collector.json
openaddr/tests/util.py
openaddr/util/__init__.py
openaddr/util/templates/collector-userdata.sh

Introduces a Chef script and utility function for preparing collections on another server. This functionality is still dark, and requires further EC2 changes before it can be exposed.

Added EC2 runner for collection process

---

.travis.yml
circle.yml
setup.py

Forces CI to use the pip-installed version of openaddr so it will correctly fail when files aren't included in setup.py.

Removing package data prior to CI tests

---

openaddr/ci/collect_supervise.py
openaddr/run_ec2_ami.py
openaddr/tests/util.py
openaddr/util/__init__.py

So that Dotmap could benefit from high-memory instances.

Added configurable EC2 instance type to openaddr-run-ec2-command

---

openaddr/conform.py
openaddr/tests/conform.py

Hey folks - here's an implementation for a new ```format``` function in conform as proposed in https://github.com/openaddresses/openaddresses/pull/1925. It allows for more flexibility than ```join``` when mapping multiple input fields to a single field in the output CSV.
Given the following config:
```json
{
"conform": {
"number": {
"function": "format",
"fields": ["a", "b", "c"],
"format": "$1$2-$3"
}
}
}
```
and these inputs:
```json
{"a": "1", "b": "B", "c": "3"}
```
It will produce ```{"OA:number": "1B-3"}```.
If one of the variables is NULL/empty, its left context will be omitted, except for any initial string that appears before the first variable occurrence. So for the format string above, if "c" is NULL, it will produce ```{"OA:number": "1B"}```, omitting the hyphen.
This is one …

Format function for conform

---

openaddr/conform.py
openaddr/tests/conform.py

The current join function in conform assumes that all fields are non-NULL/non-empty. This change will simply ignore empty/NULL fields in the join so values like "1/" or "1-" don't end up in the output when one of the join fields is missing.

handling NULL/empty values in the join function in conform

---

openaddr/cache.py
setup.py

- Updates pyesridump to 1.4.0 to bring in better EsriJSON to GeoJSON conversion (it was incorrectly converting MultiPolygons)
- Add code to skip Esri geometries that have NaN coordinates (the root cause of [this source failure](http://s3.amazonaws.com/data.openaddresses.io/runs/110497/output.txt))

Update pyesridump and filter out Esri geometries with NaN coordinates

---

chef/role-webhooks.json
chef/webhooks/recipes/default.rb
openaddr/ci/__init__.py
openaddr/ci/webauth.py
openaddr/tests/ci.py

On production CI system, `X-Forwarded-Proto` header is not reliably present so explicit OAuth callback URL configuration is necessary.
Part of #378.

Fixed GitHub OAuth callback behavior

---

openaddr/ci/__init__.py
openaddr/tests/ci.py

Re-run flag forces sources to be processed fresh, even if they're within `ci.RUN_REUSE_TIMEOUT`. Part of #378.

Add Re-Run flag to task queue

---

chef/crontab/recipes/default.rb
chef/role-crontab.json

In preparation for a server move, we need to get certain mystery files out of `/etc` and into chef. This PR starts the process with extract collection.

Start moving crontab jobs to chef recipe

---

openaddr/ci/templates/base.html
openaddr/ci/webauth.py

Specifically when someone is not a member of the OA org. Also ask for `org:read` scope to hopefully make this less of an issue.
Closes #417.

Show messages when login fails

---

.travis.yml
chef/openaddr-prereqs/recipes/default.rb
circle.yml

Earlier today, [ubuntugis-stable](https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa) upgraded from GDAL 1.11 to 2.0, and it appears that PPAs do not continue to make old packages available. I don't want to make the jump to GDAL 2.x just yet, so I’ve copied specific versions of packages to a new [OpenAddresses CI PPA](https://launchpad.net/~openaddresses/+archive/ubuntu/ci) and updated the tests to use it.
Closes #431.

Fix CI package dependencies

---

openaddr/ci/webhooks.py
openaddr/tests/ci.py

Fixes this notification due to someone crawling us:
```
ERROR: openaddr.ci.webcommon - GET /jobs/login.cgi
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/openaddr/ci/webcommon.py", line 16, in decorated_function
return route_function(*args, **kwargs)
File "/usr/local/lib/python3.4/dist-packages/openaddr/ci/webhooks.py", line 164, in app_get_job
file_tuples = [(sha, path) for (sha, path) in job.task_files.items()]
AttributeError: 'NoneType' object has no attribute 'task_files'
```

Returning 404 for non-existent job

---

openaddr/ci/objects.py
openaddr/ci/templates/source.html
openaddr/ci/webhooks.py
openaddr/tests/ci.py

This is a super-primitive approach, and I am looking for feedback. I spoke with @iandees about the content of these pages, and we agreed to get broader feedback in Slack. So, I’m going to merge and deploy this immediately, then source histories will be visible at URLs like these:
- https://results.openaddresses.io/sources/us/nm/taos
- https://results.openaddresses.io/sources/us/nd/dickinson
- https://results.openaddresses.io/sources/au/city_of_canberra
- https://results.openaddresses.io/sources/mx/hidalgo/statewide
- https://results.openaddresses.io/sources/us/il/mcdonough
Closes #446.

Add primitive source history view

---

openaddr/cache.py
openaddr/tests/cache.py

Fixes errors during cache like this:
http://s3.amazonaws.com/data.openaddresses.io/runs/121639/output.txt

Don't die if the Esri server can't handle count

---

openaddr/conform.py

There is more to the error we see in results like [this](http://s3.amazonaws.com/data.openaddresses.io/runs/127169/output.txt). According to [this StackOverflow suggestion](http://stackoverflow.com/a/27573967), I'm [installing a GDAL error handler](http://pcjericks.github.io/py-gdalogr-cookbook/gdal_general.html#install-gdal-ogr-error-handler) and logging out what it gives us.

Use a GDAL error handler to extract more info on error

---

openaddr/preview.py
openaddr/tests/preview.py

Uses a temporary file with packed float values to store points outside of RAM, and catch geometry transformation errors.
Closes #455.
Closes #454.

Support more preview points than fit in memory

---

openaddr/ci/objects.py
openaddr/ci/templates/runs-table.html
openaddr/tests/ci.py

We want to see copied runs if they are merged to master, for recent changes beyond the weekly batch sets.

Showing more merged sources in history view

---

openaddr/ci/objects.py
openaddr/conform.py
openaddr/process_one.py
openaddr/tests/__init__.py
openaddr/tests/ci.py

Adds a "source problem" field to run states, which will later make it possible to display meaningful output in run tables.
Part of #460.

Categorize source failures

---

chef/crontab/recipes/default.rb
openaddr/run_ec2_ami.py
openaddr/tests/util.py
openaddr/util/__init__.py
openaddr/util/templates/task-instance-userdata.sh
setup.py

Task instances launched by `openaddr-run-ec2-command` will now talk to Slack and upload their own logs to S3. If this works well, the next step will be to remove the long-term supervision responsibility from the script running under cron, so that the [central scheduled task instance](https://github.com/openaddresses/machine/blob/master/docs/components.md#scheduled-tasks) has fewer long-running jobs to worry about, and can be restarted or replaced more frequently.

Make task instances police themselves

---

openaddr/conform.py
openaddr/tests/conform.py

See openaddresses/openaddresses#2075
These 2 functions abstract the common `regexp` patterns in use for US (and other country) sources.  By internalizing these 2 commons patterns, modifications can be implemented without having to modify the many sources that use these patterns.
Its current implementation only covers a few basic scenarios:
- `number` is only defined as optional whitespace + 1 or more digits + at least one whitespace
- `street` is defined as anything after `number`
2 functions were used instead of a single function that writes both `number` and `street` fields in the event that the source already contains a separate `number` or `street` field.
*This is my first foray into python, my apologies if it's terrible*

added `prefix_number` and `prefix_street` conform functions

---

chef/openaddr-prereqs/recipes/default.rb
openaddr/ci/objects.py
openaddr/process_one.py
openaddr/tests/ci.py
setup.py

In #462, I accidentally confused `code version` with `version` (an outdated cache-related property).

Fixed confusion between run state "version" and "code version"

---

chef/openaddr-prereqs/recipes/default.rb
setup.py

Seeing some weirdness and conflicts between apt-gotten `awscli` and pip-installed `awscli`.

Fixing awscli/botocore dependency

---

.travis.yml
circle.yml

Since running the Chef cookbooks on Ubuntu 14.04 install python 3.4, it would be good to run the test suites using that version.

Run tests on Travis and CircleCI using python 3.4

---

openaddr/ci/__init__.py
openaddr/ci/collect.py
openaddr/ci/work.py
openaddr/tests/__init__.py
openaddr/tests/ci.py
openaddr/tests/util.py
openaddr/util/__init__.py

When used with IAM Roles, `generate_url()` was appending tokens to generated URLs. Replaced with a dumber string-building function.

Removed all uses of boto.s3.key.generate_url()

---

chef/crontab/recipes/default.rb
openaddr/ci/tileindex.py

Remove AWS key/secret args from openaddr-index-tiles

---

chef/crontab/recipes/default.rb
chef/data/local.json
chef/webhooks/recipes/default.rb
openaddr/ci/enqueue.py
openaddr/ci/run_dequeue.py
openaddr/tests/util.py
openaddr/util/__init__.py

`openaddr.ci` namespace was used all over the place; this change configures it explicitly.
Part of #472.

Configure CloudWatch namespace

---

openaddr/conform.py
openaddr/tests/conform.py

These functions were originally named `prefix_number` and `prefix_street` and targeted at inputs like `102 E Maple Street`.  It was agreed that these functions were misnamed since the latter implies that the street is the prefix whereas it's actually the postfixed part of the input.  The new functions are more appropriately named.

renamed functions to `prefixed_number` and `postfixed_street`

---

openaddr/ci/dashboard_stats.py
openaddr/ci/templates/dashboard.html
openaddr/ci/webhooks.py
openaddr/tests/dashboard_stats.py
test.py

Adds a view at `/dashboard` which reflects a static point-in-time display of OA stats. Dynamic updating to come later.

Add basic stats view

---

openaddr/conform.py
openaddr/tests/conform.py

This PR adds sub-address (not units) support to the `prefixed_number` and `postfixed_street` regexes.  Some extraction examples:
* `123 3rd Street` yields `123` as number and `3rd Street` as street
* `123a 3rd Street` yields `123a` as number and `3rd Street` as street
* `123-a 3rd Street` yields `123-a` as number and `3rd Street` as street
Additionally, there is an error in `prefixed_number_pattern` regex that was extracting, for example, `3` from `3rd Street` which creates an erroneous number for numberless ordinal street names.  This appears to be a common problem with a lot `regexp` [implementations](https://github.com/openaddresses/openaddresses/blob/master/sources/us/ak/matanuska_susitna_borough.json#L20) that have copy/pasted the common `number` regex of `"^([0-9]+)"`:
```
>>> …
```

fixed prefix/postfix regexes to include subaddresses (not units)

---

openaddr/conform.py
openaddr/tests/conform.py

Adds conform functions `remove_prefix` and `remove_postfix` that remove another fields' value from the beginning or end of a field.  
Fixes #479 (see for examples)

Add remove prefix and postfix functions

---

chef/crontab/recipes/default.rb
openaddr/ci/__init__.py
openaddr/ci/collect.py
openaddr/ci/dashboard_stats.py
openaddr/ci/sum_up.py
setup.py

Map rendering and machine stats for dashboard should happen more frequently, and outside heavy zipfile collections. This will also be a place for GeoJSON rendered output for #480.

Move periodic summing-up tasks

---

openaddr/conform.py
openaddr/tests/conform.py

`remove_postfix` has a bug where a zero-length `field_to_remove` value was causing the entire `field` to be assigned an empty string instead of not modifying the value.  
Also added zero-length `field_to_remove` value test to `remove_prefix` for thoroughness.

Fix remove_prefix and remove_postfix functions

---

openaddr/ci/__init__.py
openaddr/ci/objects.py
openaddr/render.py
openaddr/tests/ci.py
openaddr/tests/summarize.py

- Added `source paths` and `source count` fields to GeoJSON output
- Started using actual source paths instead of blob hashes
- Fixed GeoJSON mime-type in S3
- Introduced rules for Run.source_path values
- Stopped outputting unneeded U.S. and Europe GeoJSON
Part of #480.

Fix GeoJSON render bugs

---

openaddr/ci/collect.py
openaddr/ci/schema.pgsql
openaddr/ci/templates/index.html
openaddr/tests/ci.py

Add South America collection

---

openaddr/ci/objects.py
openaddr/ci/work.py
openaddr/process_one.py
openaddr/slippymap.py
openaddr/tests/__init__.py
openaddr/tests/ci.py
openaddr/tests/slippymap.py
test.py

Generates MBTiles with Tippecanoe alongside preview renders, but does nothing with them except upload to S3. Second step of #466.

Add secret MBTiles rendering to rendered output

---

chef/crontab/recipes/default.rb

Timed out at 12 hours, so extended this limit to 18 hours.

Extended run time for extract collections

---

openaddr/ci/enqueue.py
openaddr/ci/run_dequeue.py

Should have the effect of speeding up quick jobs near the end of a batch set.

Reduced sleep times in enqueue and dequeue loops

---

openaddr/dotmap.py

Should prevent entire sources from being read into memory. Closes #526.

Replaced all-at-once read with streamed zipfile open

---

chef/crontab/recipes/default.rb
chef/data/local.json
chef/worker/recipes/default.rb
lambda.py
openaddr/run_ec2_ami.py
openaddr/tests/util.py
openaddr/util/__init__.py
openaddr/util/templates/task-instance-userdata.sh

Instead of talking to Slack directly, I'm connecting SNS to Slack via [a new AWS Lambda function](https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions/OA-Slack?tab=code). This should soon remove the need for a Slack configuration setting and allow AWS configuration to handle messaging.

Switch Slack status updates to SNS

---

chef/crontab/recipes/default.rb
openaddr/tests/util.py
openaddr/util/__init__.py
openaddr/util/templates/task-instance-userdata.sh

Use ephemeral instance storage to increase the tmp volume available to Tippecanoe. Another approach here would increase the size of the root volume, if this doesn't work.
Closes #542.

Fix dotmaps temp space

---

openaddr/conform.py
openaddr/tests/__init__.py
openaddr/tests/sources/us-or-curry.json

Curry, OR tests were incorrectly failing in https://github.com/openaddresses/openaddresses/pull/2562. This PR adds use of `conform_smash_case()` where it was missing.

Fix source test case-smashing

---

.gitignore
Vagrantfile
docs/install.md

Follow-on to PR #559 based on feedback from @trescube:
* added `.vagrant` directory to `.gitignore` since this should never get checked in
* mount host directory into guest at `/home/vagrant/machine` so it's clearer that there's a relationship between the files on your development are the same files inside the VM
* update docs to reflect new directory name
* I hate trailing whitespace... my editor cleaned up a bunch of it (I can undo those changes if that's annoying)
I ran through this on a fresh VM without any issues.

Move mounted vagrant folder from /vagrant to /home/vagrant/machine

---

chef/webhooks/recipes/default.rb
openaddr/ci/__init__.py
openaddr/ci/templates/job.html
openaddr/ci/webhooks.py

The experimental slippy map tile server now has a name at http://dotmaps.openaddresses.io thanks to @iandees. Closes #565.

Added link to slippy map previews

---

setup.py

Use the more recent, faster version of pyesridump.

Bump to pyesridump 1.6.0

---

openaddr/ci/__init__.py
openaddr/ci/objects.py
openaddr/ci/queuedata.py
openaddr/ci/work.py
openaddr/tests/ci.py

Instead of passing around mysterious plain dictionaries, use `objects.RunState` class to more reliably move state data around. Adds substantial tests for `ci.pop_task_from_taskqueue()` and replaces `ci.work.assemble_output()` with `ci.work.assemble_runstate()`.

Use RunState objects

---

openaddr/ci/objects.py
openaddr/ci/templates/job.html
openaddr/ci/webhooks.py
openaddr/ci/work.py
openaddr/tests/ci.py

For new runs, include the ID in the state so it’s easier to build URLs. Closes #567.

Add RunState.run_id property

---

openaddr/process_one.py
openaddr/util/__init__.py

Adds log lines for CPU, memory, disk, and network usage to all process logs. Output will look like this in 30 second increments:
```
2017-03-26 18:11:36,372     INFO: Resource usage: 4% user, 3% system, 438MB memory, 0KB read, 0KB written, 70KB sent, 2700KB received, 3sec elapsed
2017-03-26 18:11:39,389     INFO: Resource usage: 4% user, 9% system, 438MB memory, 0KB read, 0KB written, 72KB sent, 2699KB received, 6sec elapsed
2017-03-26 18:11:42,367     INFO: Resource usage: 11% user, 86% system, 439MB memory, 0KB read, 2036KB written, 2KB sent, 1KB received, 9sec elapsed
2017-03-26 18:11:45,394     INFO: Resource usage: 14% user, 85% system, 439MB memory, 0KB read, 2972KB written, 0KB sent, 0KB received, 12sec elapsed
2017-03-26 18:11:48,379     INFO: Resource usage: 15% user, 84% system, …
```

Measure resource usage in run logs

---

openaddr/tests/util.py
openaddr/util/__init__.py

Uses child processes when counting, and logs at the end at least once. Closes #593.
There is some slightly dubious stuff here with CPU when the Tippecanoe process disappears, but it’s now less-wrong than when Tippecanoe wasn’t counted at all.

Update resource logging

---

openaddr/slippymap.py
openaddr/tests/slippymap.py

Modified openaddr.slippymap to accept multiple filenames or URLs for sources, to make it easier to generate vector tilesets for multi-source countries.
1. Install Machine for [local development using Vagrant](https://github.com/openaddresses/machine/blob/master/docs/install.md#local-development).
2. Log in to the Vagrant machine, and ensure that openaddr.slippymap is available by running this command:
cd ~/machine
python3 -m openaddr.slippymap --help
You should see usage help like this:
usage: slippymap.py [-h] [-v] [-q]
mbtiles_filename [src_filenames [src_filenames ...]]
Generate a single source slippy map MBTiles file with Tippecanoe.
3. Additionally install Tippecanoe on the Vagrant image:
sudo ~/machine/chef/run.sh dotmap
4. Generate a vector tiles MBTiles file. This example combines …

Improve Tippecanoe commandline

---

openaddr/dotmap.py

The homepage map shows dot density, but it could also be used to investigate the dots themselves. This PR starts uploading a much larger MBTiles file to Mapbox, per conversation with @ingalls this morning.

Stopped dropping properties in dotmap call to Tippecanoe

---

openaddr/ci/__init__.py

`ci.TASK_QUEUE_2` will be used to test Docker workers for https://github.com/openaddresses/machine/pull/587, and later removed.

Writing webhook-sourced jobs to a second tasks queue

---

openaddr/process_one.py
openaddr/tests/__init__.py

Fixed argument order to slippymap.generate in render_slippymap()

---

openaddr/run_ec2_ami.py
openaddr/tests/util.py
openaddr/util/templates/task-instance-userdata.sh

When starting an EC2 task instance, run under Docker instead of Chef. Keep Chef around for the moment for the Cronbox itself for now.

Switched to using Docker runs for cron-driven processes

---

chef/crontab/recipes/default.rb
openaddr/dotmap.py
openaddr/run_ec2_ami.py
openaddr/tests/util.py
openaddr/util/__init__.py

Replaces EC2 instance storage knowledge with dumber `--temp-size` flag to `openaddr-run-ec2-command`.
Closes #604.

Expand temp space available to Dotmap instances

---

openaddr/ci/__init__.py

Same-start-time jobs from Cron were stepping on each other. Followup to #609, closes #608.

Added PID to log stream name

---

openaddr/ci/__init__.py
openaddr/tests/ci.py
test.py

When a rate limit exception is raised, save the log message and try again later.
Closes #612.

Throttle Cloudwatch logs

---

.travis.yml
chef/crontab/recipes/default.rb
openaddr/ci/coverage/calculate.py
ops/.gitignore
ops/Makefile
ops/run-ec2-command.py
ops/update-scheduled-tasks.py

Moved `openaddr-collect-extracts` task to a new equivalent `OA-Collect-Extracts` Cloudwatch rule and Lambda function `OA-EC2-Run-Task`. Part of #617.

Move one EC2 task from cronbox to lambda

---

openaddr/ci/__init__.py
openaddr/ci/schema.pgsql

The old way was creating duplicate worker IDs under Docker. This should be slightly smarter.

Switched worker ID from uuid.getnode() to socket.gethostname()

---

chef/crontab/recipes/default.rb
ops/run-ec2-command.py
ops/update-scheduled-tasks.py

Moved `openaddr-calculate-coverage` task to a new equivalent `OA-Calculate-Coverage` Cloudwatch rule. Added version support to `OA-EC2-Run-Task ` function. Part of #617.

Move second EC2 task from cronbox to lambda

---

chef/crontab/recipes/default.rb
ops/run-ec2-command.py
ops/update-scheduled-tasks.py

Moved `openaddr-update-dotmap` task to a new equivalent `OA-Update-Dotmap` Cloudwatch rule. Added temp-size support to `OA-EC2-Run-Task ` function. Part of #617.

Move third EC2 task from cronbox to lambda

---

chef/crontab/recipes/default.rb
ops/update-scheduled-tasks.py

Moved `openaddr-index-tiles` task to a new equivalent `OA-Index-Tiles` Cloudwatch rule. Shortened code in `update-scheduled-tasks.py` to a loop. Part of #617.

Move fourth EC2 task from cronbox to lambda

---

chef/crontab/recipes/default.rb
ops/update-scheduled-tasks.py

Moved `openaddr-enqueue-sources` task to a new equivalent `OA-Enqueue-Sources` Cloudwatch rule. Added explicit version number to `update-scheduled-tasks.py` to a loop. Part of #617.

Move fifth EC2 task from cronbox to lambda

---

chef/crontab/recipes/default.rb
openaddr/ci/sum_up.py
ops/Procfile-webhook

Moved `openaddr-sum-up-data` task to a new equivalent task in the webhooks Procfile for Honcho. Added hourly running option to `openaddr-sum-up-data` to a loop. Closes #617.

Move final EC2 task from cronbox to webhooks

---

openaddr/conform.py
openaddr/tests/conform.py

Hey all -  finally found a minute to implement this.
In some cases it would be useful to have the ability to apply more than a single standard conform function to a given field. One example is the city of Wichita, KS in https://github.com/openaddresses/openaddresses/pull/2423, where there's a "Prop_Addr" field which contains number, street, and sometimes unit, and also a separate unit field which needs to be removed from the street name. Ideally we could run a "postfixed_street" to separate the street (+unit) from the initial house number, and then remove the unit suffix with a "remove_postix". However, the conform only allows running a single function per field. It might be possible to devise a (nasty) regex to handle all of the cases, but said regex might be brittle if e.g. the data …

"chain" conform function

---

openaddr/dotmap.py
openaddr/tests/dotmap.py
ops/update-scheduled-tasks.py

We added properties to the dotmap output in https://github.com/openaddresses/machine/pull/620, and then removed them again in https://github.com/openaddresses/machine/commit/b45f73a251bbb6ebdc1ccba517b717f791d49e37 when the output cracked the 500KB-per-tile limit. This change attempts to introduce properties only at the highest zoom level, 14, per advice from @ericfischer on using `tile-join` to combine tilesets built with different property settings.
Closes #626.

Creating two Tippecanoe tilesets and merging them

---

openaddr/ci/worker.py

Closing the connection when it’s done; thought this was implied when using `connect()` in a Python context [but seemingly not](http://initd.org/psycopg/docs/usage.html#with-statement).
Part of #613.

Explicitly closing the DB connection in worker

---

openaddr/ci/__init__.py

When most work is cached, no heartbeats from workers get registered and they get reaped.
Part of #613.

Moved initial worker heartbeat up to prevent it from nodding off

---

circle.yml
docs/install.md

This is in response to #641
* Adds command for CircleCI to tag the `prereq` and `machine` images with `latest` tag
* Pushes `latest` tag to Docker Hub
* Updates docs for consistency to avoid issues reported in #641 
And my editor deleted a bunch of whitespace in the `install.md`. 
From an ✈️ :)

Publish latest docker tag for images on Docker Hub

---

circle.yml

Add numeric tags for major versions, like `openaddr/machine:6` instead of confusing `openaddr/machine:6.x`. First followup to #642.

Fiddle docker tags

---

Dockerfile-machine
circle.yml
docker-compose.yml
docs/install.md

Remove pre-numeric tags for major versions, like `openaddr/machine:6.x` and use newer ones like `openaddr/machine:6`. Second followup to #642.

Fiddle Docker tags more

---

openaddr/ci/coverage/calculate.py

This should ease up on some of the meaningless log messages we see each time `openaddr-calculate-coverage` is run.

Added gdal.PushErrorHandler to quiet some annoying error logging

---

openaddr/conform.py
openaddr/tests/conform.py

Modifies `prefixed_number` and `postfixed_street` regexes to parse fractional house numbers:
- `123 1/2 Main Street` into `123 1/2` (number) and `Main Street` (street)
- `123-3/4 Main Street` into `123-3/4` (number) and `Main Street` (street)
Also reorganizes regexes for clarity.

added support for fractional house numbers

---

openaddr/conform.py
openaddr/tests/conform.py

This functionality is required for sources that utilize the `format` function but have floating point field values referenced as not-the-last field.  For example, if the final `number` field value is `349.0`, then `row_canonicalize_unit_and_number` removes the `.0` suffix.  However, `format` can reference multiple fields and if one of any but the last field is a floating point number, then the `.0` is embedded and cannot be removed, for example `576.0` and `B` are concatenated to `576.0B`.  This fix applies the same if-the field-value-ends-with-`.0`-then-remove-it-before-appending to the individual field values of the `format` function.  
Fixes openaddresses/openaddresses#3009

strip out '.0' suffix in format component fields

---

circle.yml

Switching to numeric tags in https://github.com/openaddresses/machine/pull/643 and https://github.com/openaddresses/machine/pull/642 seems to be confusing Circle or Docker, and leading to lengthy rebuilds in CI. I think this might be because "6" is a valid truncated image tag, while "v6" might not be? Add "v6" tags to test this idea.

Added "v6" style Docker image tags

---

openaddr/util/__init__.py

Invoking `machine` with Docker works great but I ran into a few errors when developing inside the container. I think this is due to some errors in the logging system related to too-cute new symlink additions to `/proc`.
This PR does not represent complete comprehension of the issue but mostly just me trying to make the relevant codepaths avoid the problem (I think the new additions to `/proc` are not of interest to us). I think this is probably justified but welcome feedback or suggestions that I be less lazy.
cc @migurski

avoid reads of invalid /proc resources

---

openaddr/conform.py
openaddr/tests/conform.py

This PR aims to handle sources where units may be embedded in a single address field and makes 2 modifications:
- adds a function named `postfixed_unit` 
- adds an optional boolean flag named `may_contain_units` to the `postfixed_street` function
A number of sources like [Thurston County, WA](https://github.com/openaddresses/openaddresses/blob/master/sources/us/wa/thurston.json#L26) implement highly similar regex patterns to extract common unit formats from fields that contains streets.  This PR adds convenience functions to reduce copy/pasting of these patterns.  These unit designators are the tokens (the most common I've seen):
- Unit
- Apartment
- Apt
- Suite
- Ste
- Building
- Bldg
- Lot
- `#`
Much like `prefixed_number` and `postfixed_street`, `postfixed_unit` is specified as:
```
{ …
```

add condition to postfixed_street for optional units

---

openaddr/conform.py

https://github.com/openaddresses/machine/blob/20e0f515653456ce3cff0519530771736eb352e5/openaddr/conform.py#L998 smashes case of the conform object however it fails to do this for [compound functions](https://github.com/openaddresses/openaddresses/blob/master/ATTRIBUTE_FUNCTIONS.md#compound-functions).
This leads to confusing error messages to the user when it fails when both the conform object and source use CAPS.
Workaround is for users to use lowercase in their conform object until this is merged.
PS. I'm not a python coder, so feel free to refactor this code if you need to.

ensure compound functions are conform smash cased

---

openaddr/ci/__init__.py
openaddr/process_one.py
openaddr/tests/__init__.py

`openaddr-process-one` was still expecting a Mapzen key.

Removed additional remaining references to Mapzen

---

openaddr/conform.py
openaddr/tests/conform.py

This PR adds a function called `first_non_empty` that takes a string array in `fields` to return the first value that's not empty or trimmable to a zero-length string.  A use case for this is the latest [SEMCOG, TX data](https://services5.arcgis.com/8DjE4f6iFLArDhsU/arcgis/rest/services/AddressPoints_Jan2016/FeatureServer/0) where both `MUNICIPAL` and `POSTAL_COM` can contain city names.  In some cases only one of these is populated and in some cases both are populated.  One should be preferred but there's currently no way to only include one value.  I'll add to the [attribute functions](https://github.com/openaddresses/openaddresses/blob/master/ATTRIBUTE_FUNCTIONS.md) once released, but an example usage of this would be:
```json
{
"city": {
"function": "first_non_empty",
"fields": …
```

added first_non_empty helper function

---

circle.yml
ops/run-ec2-command-userdata.sh

Scheduled tasks weren’t working, due to missing Docker image tags. Use `docker tag` to provide correct tags, prune some unused images, and revert scheduled task userdata.

Fiddle with Docker tags

---

openaddr/ci/webhooks.py

We’re seeing a lot of annoying attack traffic generating errors. Catch badly-formatted input and return an HTTP 400 so it doesn't generate an alert.

Suppress dumb errors

---

openaddr/ci/webhooks.py

Missed on in #684: catch badly-formatted input and return an HTTP 400 so it doesn't generate an alert.

Suppress one more dumb error

---

openaddr/ci/templates/dashboard.html

Graphs on [dashboard](http://results.openaddresses.io/dashboard) were not suit for the latest statistics:
* Successful Sources was out of range, increasing max from 1500 to 2000, before/after: 
* Address counts per source histogram had a large spike at right, doubled max from 200,000 to 400,000 for a better fit: before/after:

Update graph ranges to suit latest statistics better

---

openaddr/ci/objects.py
openaddr/ci/schema.pgsql
openaddr/ci/sum_up.py

Start keeping index page inclusion in an explicit column using hourly `openaddr-sum-up-data` process.
Part of #710.

Add new runs.for_index_page column and keep it updated

---

README.md
openaddr/ci/templates/dashboard.html
openaddr/ci/templates/index.html
openaddr/ci/templates/job.html
openaddr/ci/templates/runs-table.html
openaddr/ci/templates/source.html
openaddr/ci/webcommon.py
openaddr/ci/webhooks.py
openaddr/tests/ci.py
openaddr/util/__init__.py

This passes most of the URLs on results.openaddresses.io through a filter to clean up any URLs that refer to S3 directly so that they can be served via the CDN at data.openaddresses.io instead.

Don't expose the S3 bucket URLs

---

openaddr/__init__.py
openaddr/tests/__init__.py

This is to handle 403's after I removed support for `public-read` ACLs on the `data.openaddresses.io` bucket today.

Handle bucket-in-domain and bucket-in-path forms of S3 URL

---

openaddr/dotmap.py
openaddr/tests/dotmap.py

For https://github.com/openaddresses/openaddresses.io/issues/77 
Looking at [the logs](https://s3.console.aws.amazon.com/s3/object/data.openaddresses.io/logs/2019-10-01-15-01-openaddr-update-dotmap/cloud-init-output.log.gz?region=us-east-1&tab=overview), the dotmap build was failing because tippecanoe couldn't successfully write out all the features at our chosen base zoom level of 15:
```
tile 15/16593/11212 has 201699 features, >200000    
Try using -B (and --drop-lines or --drop-polygons if needed) to set a higher base zoom level.
...
*** NOTE TILES ONLY COMPLETE THROUGH ZOOM 14 ***
...
Traceback (most recent call last):
File "/usr/local/bin/openaddr-update-dotmap", line 11, in <module>
load_entry_point('OpenAddresses-Machine==7.2.13', 'console_scripts', 'openaddr-update-dotmap')() …
```

Tell tippecanoe to drop densest points as needed

---

openaddr/ci/objects.py
openaddr/dotmap.py
openaddr/tests/ci.py

These queries were causing the dotmap to never finish (https://github.com/openaddresses/openaddresses.io/issues/77#issuecomment-540818005), so I tried to make them simpler while doing the same thing.
From my cursory testing it seems that this returns the expected result. I was never able to get the original query to finish, so I can't be certain that it's returning the exact same result. The number of rows returned by the two queries seems to make sense and looking at the run IDs returned by each seem to make sense.

Possibly simplify the completed runs query?

---

ops/run-ec2-command-userdata.sh

One of the dotmaps failed recently because it ran out of disk space. Turns out the /tmp dir hasn't been mounted from the EBS volume, so this fixes that.

Mounts are at /dev/nvme1 now instead of /dev/xvdb

---

.circleci/config.yml
openaddr/__init__.py
openaddr/cache.py
openaddr/ci/__init__.py
openaddr/ci/templates/dotmap-index.html
openaddr/ci/templates/dotmap-scene.yaml
openaddr/ci/templates/job.html
openaddr/ci/web.py
openaddr/ci/webdotmap.py
openaddr/ci/webhooks.py
openaddr/conform.py
openaddr/tests/ci.py
openaddr/util/__init__.py
setup.py

This uses a Python SQLite library called apsw that supports virtual filesystems. It also implements an S3-backed filesystem that makes calls to the CI-built mbtiles files.
Since the S3-backed filesystem is making a ton of calls out to S3 (it's reading 1KB blocks at a time basically), I used the memcache client to help alleviate some of the S3 calls. I'd still like to figure out how to grab bigger chunks of the S3 file and warm the cache more, but this is "good enough" for now. There's also memcache caching for the tiles themselves and I also tell the browser to cache the responses for a year to try reducing calls in the first place.

Moving support for slippy dotmaps in CI previews to machine

---

openaddr/ci/webdotmap.py

I used `abort(404)` in the code I added in #761, but it raises exceptions and the SNS alerting/interception makes a bunch of noise. Instead, just return text and a status code.

Don't use abort(404) to save on SNS noise

---

openaddr/cache.py

Currently, it is not possible to process sources using the `application/vnd.geo+json` mime type, as a somewhat-random file extension is assigned instead of `.json`.
This change adds this additional mime type to the list of known mime types in the `mimetypes` python library.
Here's an example of a source that fails because of the incorrect file extension.
```
1       316.1  DEBUG: Requesting https://planning.kimberley.ca/wms/layers?service=WFS&version=1.3.0&request=GetFeature&typename=Addresses&outputFormat=application%2Fvnd.geo%2Bjson with args None     1       673.6  DEBUG: Content-Type says "application/vnd.geo+json" for https://planning.kimberley.ca/wms/layers?service=WFS&version=1.3.0&request=GetFeature&typename=Addresses&outputFormat=application%2Fvnd.geo%2Bjson     1       684.1 …
```

Added support for geojson files using "application/vnd.geo+json" as the mime type

---

openaddr/ci/webhooks.py

This is a bug that resulted from switching over to the V2 schema. The workers couldn't process the sources, but inserted entries into the database with `processed` left null. This caused the `good_runs` list to be empty and to get an exception on these lines.
e.g.
```python
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File …
```

Handle the case where none of the runs are processed

---

openaddr/ci/work.py
openaddr/process_one.py
openaddr/tests/ci.py

Machine already supported V2 sources since #691, but it only made assumptions about the V2 `layer` and `layersource` it should use when the sources were still V1. When we switched sources to V2 schema in https://github.com/openaddresses/openaddresses/pull/5165, `process-one` stopped making the assumption for layer and layersource and started failing instead.
This PR changes the logic for the CI worker to default to layer `addresses` and layersource `primary`.

Basic support for v2 sources in machine

---

openaddr/conform.py

According to the documentation 
https://github.com/openaddresses/openaddresses/blob/master/ATTRIBUTE_FUNCTIONS.md
we should use "get" function name. I hope it's going to work this time...

Changed mistaken key value for get function

---

Dockerfile-prereqs

The CI build is failing because of a SyntaxError. I tracked it down to https://github.com/pypa/setuptools/issues/2541. This is an attempt to use one of the workarounds mentioned there.

Attempt a workaround for a Ubuntu Python packaging bug
