openaddresses/machine

- openaddr/process_all.py
- openaddr/render.py
> Show status color

- openaddr/conform.py
- test.py
> Added geometry type detection for ESRI sources

- README.md
- openaddr/cache.py
- openaddr/conform.py
- openaddr/util/esri2geojson.py
- setup.py
- test.py
Added `openaddr-esri2geojson`, closes #71.
> Added ESRI conversion script

- openaddr/process_all.py
- openaddr/templates/conform-result.vrt
- setup.py
- test.py
Packages output CSV files into zip archives for faster downloads, and includes [OGR virtual raster](http://www.gdal.org/drv_vrt.html) for ease of opening in geo software.
Closes #56.
> Zip output files

- README.md
- openaddr/process_all.py
- openaddr/summarize.py
- openaddr/templates/user-data.sh
> Add source path argument

- openaddr/cache.py
We need this to get us-tx-san_antonio working since the certificates the website is serving are still broken.
> Add verify_ssl flag that disables SSL cert verification when set to false

- chef/role-webhooks.json
- chef/role-worker.json
- chef/webhooks/recipes/default.rb
- chef/worker/recipes/default.rb
- openaddr/ci/__init__.py
- openaddr/ci/run_dequeue.py
- openaddr/ci/worker.py
Requires three new optional configuration variables, tells AWS all about events and state.
Closes #120.
> Added SNS errors and Cloudwatch reporting

- openaddr/conform.py
- openaddr/tests/__init__.py
- openaddr/tests/conform.py
- openaddr/tests/sources/us-ca-carson.json
Include the `city`, `district`, and `region` fields in the output CSV.
> Add some fields to the output CSV

- openaddr/ci/__init__.py
- openaddr/ci/worker.py
- openaddr/tests/ci.py
> Push worker results to S3 

- openaddr/ci/__init__.py
- openaddr/ci/worker.py
- openaddr/tests/ci.py
> Storing base64-encoded sources in queue and runs

- README.md
- openaddr/ci/templates/job.html
> Document CI

- openaddr/ci/__init__.py
- openaddr/ci/schema.pgsql
- openaddr/tests/ci.py
> Expand runs table

- openaddr/ci/__init__.py
- openaddr/ci/schema.pgsql
> Added runs.datetime_tz column to store additional datetime

- openaddr/ci/__init__.py
- openaddr/ci/schema.pgsql
> Removed vestigial runs.datetime column

- README.md
- chef/Procfile-webhook
- chef/worker/recipes/default.rb
- openaddr/ci/__init__.py
- openaddr/ci/enqueue.py
- openaddr/ci/webhooks.py
- openaddr/tests/ci.py
- run-debug-webhooks.py
- setup.py
> Move app down into Flask Blueprint

- openaddr/ci/objects.py
- openaddr/ci/schema.pgsql
- openaddr/ci/templates/info.html
- openaddr/ci/templates/job.html
- openaddr/ci/templates/jobs.html
- openaddr/ci/templates/set.html
- openaddr/ci/templates/sets.html
- openaddr/ci/webhooks.py
- openaddr/tests/ci.py
> Add new views

- openaddr/ci/__init__.py
- openaddr/ci/enqueue.py
- openaddr/ci/objects.py
- openaddr/ci/schema.pgsql
- openaddr/render.py
- openaddr/tests/ci.py
* ~~Categorize run results with different kinds of failure.~~
Closes #169.
> Expand sets table

- openaddr/ci/objects.py
- openaddr/ci/templates/run-sample.html
- openaddr/ci/templates/set.html
- openaddr/ci/webhooks.py
- openaddr/summarize.py
- openaddr/templates/state.html
- openaddr/tests/ci.py
- openaddr/tests/summarize.py
> Moved sample JSON to AJAX requests

- openaddr/ci/objects.py
- openaddr/ci/schema.pgsql
- openaddr/ci/templates/set.html
- openaddr/ci/webhooks.py
- openaddr/summarize.py
- openaddr/tests/ci.py
- openaddr/tests/summarize.py
> Add aggregate view front page

- openaddr/ci/collect.py
- openaddr/tests/ci.py
- setup.py
- test.py
Script to generate `openaddresses-collected.zip`; does not yet reflect results in site HTML.
Part of #88 and #182.
> Add zip collections

- openaddr/ci/collect.py
- openaddr/ci/webhooks.py
- openaddr/summarize.py
- openaddr/tests/ci.py
- openaddr/tests/summarize.py
> [WIP] Add more zip collections

- openaddr/ci/templates/job.html
- openaddr/ci/templates/runs-table.html
- openaddr/ci/templates/set.html
- openaddr/ci/webhooks.py
- openaddr/ci/worker.py
- openaddr/process_one.py
- openaddr/tests/__init__.py
- openaddr/tests/ci.py
* Closes #158 
* Closes #177
* Closes #187
> Fixed some longstanding bugs

- openaddr/ci/collect.py
- openaddr/tests/ci.py
> Skipping README files when building collections

- openaddr/ci/__init__.py
- openaddr/ci/collect.py
- openaddr/ci/objects.py
- openaddr/ci/static/writ.css
- openaddr/ci/templates/head.html
- openaddr/ci/templates/index.html
- openaddr/ci/templates/job.html
- openaddr/ci/templates/jobs.html
- openaddr/ci/templates/nav.html
- openaddr/ci/templates/runs-table.html
- openaddr/ci/templates/set.html
- openaddr/ci/templates/sets.html
- openaddr/ci/webhooks.py
- openaddr/tests/ci.py
> Improve html front page

- chef/ec2-hostname/recipes/default.rb
- chef/role-worker.json
- chef/worker/recipes/default.rb
Tell Slack when workers are born and die.
> Announce worker state

- openaddr/ci/__init__.py
- openaddr/ci/collect.py
- openaddr/ci/worker.py
> Improve debug interface for openaddr-ci-collect

- openaddr/ci/enqueue.py
> Moved AWS config to openaddr-enqueue-sources command-line arguments

- openaddr/ci/collect.py
- openaddr/tests/ci.py
Exception handling was hard to predict with the generator-iterator leading to incomplete uploads. Replace with a class that does the same job with less coroutine magic.
> Replace ci.collect.collect_and_publish generator-iterator with a class

- openaddr/ci/worker.py
> Clean up temporary directories more aggressively

- openaddr/cache.py
Makes the error in #242 slightly more meaningful.
It looks like the ESRI server lies sometimes saying that it supports statistics but it responds with a "Cannot complete operation" error rather than actual results.
> Better error handling for ESRI caching step

- openaddr/conform.py
> Support text as a valid sampling file type

- openaddr/conform.py
- openaddr/tests/__init__.py
- openaddr/tests/conform.py
- openaddr/tests/sources/jp-fukushima.json
> Fixed encoding problem in string licenses

- openaddr/ci/enqueue.py
- openaddr/tests/util.py
- openaddr/util/__init__.py
> Add interval for autoscale growth

- openaddr/__init__.py
- openaddr/ci/collect.py
- openaddr/ci/schema.pgsql
- openaddr/tests/ci.py
Part of #260: adds and populates `zips` table with meaningful contents.
> Add zips table to database

- openaddr/ci/objects.py
- openaddr/ci/templates/index-zip.html
- openaddr/ci/templates/index.html
- openaddr/ci/webhooks.py
> Show collection size on front page

- openaddr/conform.py
> Added row number error log in conform

- openaddr/ci/objects.py
- openaddr/tests/ci.py
> Checking `is_merged` column in read_completed_runs_to_date()

- openaddr/ci/webhooks.py
- openaddr/tests/ci.py
Some of the logic in #281 will benefit from this being available.
> Add code version to state output

- openaddr/ci/collect.py
- openaddr/tests/ci.py
> Fixed Python 2/3 problem in collect.expand_and_add_csv_to_zipfile()

- openaddr/ci/__init__.py
- openaddr/tests/ci.py
> Retry enqueued sources once

- openaddr/ci/objects.py
- openaddr/ci/webhooks.py
- openaddr/tests/ci.py
> Add latest run permalinks

- openaddr/ci/webhooks.py
- openaddr/tests/ci.py
> Add JSON collection links

- docs/components.md
- docs/persistence.md
- openaddr/ci/__init__.py
- openaddr/ci/run_dequeue.py
- openaddr/ci/worker.py
- openaddr/tests/ci.py
* ~~Periodically compile worker information.~~
Part of #298.
> Add running tally of active workers

- chef/role-worker.json
> Added worker_kind to worker chef

- chef/worker/recipes/default.rb
- openaddr/ci/__init__.py
- openaddr/ci/schema.pgsql
- openaddr/ci/worker.py
- openaddr/tests/ci.py
> Introduced heartbeats table with worker state

- openaddr/ci/__init__.py
- openaddr/ci/run_dequeue.py
Created new `expected results` metric, to combine queued tasks with active ones.
Part of #298.
> Push heartbeats to cloudwatch

- chef/Procfile-webhook
- openaddr/ci/__init__.py
- openaddr/ci/web.py
- openaddr/ci/webapi.py
- openaddr/ci/webcommon.py
- openaddr/ci/webhooks.py
- openaddr/tests/ci.py
- run-debug-webhooks.py
- test.py
> Create API Flask blueprint

- openaddr/ci/__init__.py
- openaddr/ci/templates/index.html
- openaddr/ci/web.py
- openaddr/tests/__init__.py
- setup.py
Added [Werkzeug ProxyFix middleware](http://werkzeug.pocoo.org/docs/0.11/contrib/fixers/#werkzeug.contrib.fixers.ProxyFix), based on advice from [SO question about `X-Forwarded-Proto`](http://stackoverflow.com/questions/23347387/x-forwarded-proto-and-flask). Also switched some map image locations to use S3 SSL.
Closes #317.
> Fix proxied redirects

- openaddr/ci/collect.py
- openaddr/tests/ci.py
> Fix collection unicode

- openaddr/dotmap.py
- openaddr/tests/dotmap.py
> Handling errors in Mapbox API upload for dotmaps

- chef/openaddr/recipes/default.rb
- circle.yml
- setup.py
* Uses Python 2.7.x solution from https://github.com/kennethreitz/requests/issues/2022#issuecomment-143348232
* Addresses SSL handshake bug observed in https://github.com/openaddresses/openaddresses/pull/1640
> Added support for HTTP connections with SSL handshake bug

- chef/openaddr/recipes/default.rb
- chef/role-openaddr.json
- openaddr/cache.py
- openaddr/tests/util.py
- openaddr/util/esri2geojson.py
Some sources require special tokens and headers.
Part of https://github.com/openaddresses/openaddresses/pull/1702.
> Update ESRI dumper

- openaddr/__init__.py
- openaddr/ci/__init__.py
- openaddr/ci/objects.py
- openaddr/ci/webapi.py
- openaddr/ci/webhooks.py
- openaddr/summarize.py
- openaddr/tests/__init__.py
- openaddr/tests/ci.py
- openaddr/tests/summarize.py
* ~~Use RunState in `process_one`.~~
Closes #334.
> Wrapped runs.run_state JSON in objects.RunState class

- openaddr/ci/collect.py
- openaddr/conform.py
- openaddr/tests/ci.py
- openaddr/tests/conform.py
> Generate stable IDs

- openaddr/ci/collect.py
- openaddr/tests/ci.py
Deal with version mismatches between data and code.
Closes #343.
> Handle unknown collection fields

- openaddr/__init__.py
- openaddr/ci/collect.py
- openaddr/tests/ci.py
The bucket has the multipart features, not the connection.
> Fix S3 multipart use

- chef/collector/recipes/default.rb
- docs/components.md
- docs/processes.md
- openaddr/ci/collect_supervise.py
- openaddr/tests/util.py
- openaddr/util/__init__.py
- openaddr/util/templates/collector-userdata.sh
- setup.py
Should be suitable for use in cronjob.
> Added openaddr-supervise-extract-collection script for collector instances

- openaddr/ci/__init__.py
- openaddr/tests/ci.py
> Incorporate cache time when ordered a set

- openaddr/ci/__init__.py
- openaddr/ci/collect.py
- openaddr/ci/collect_supervise.py
- openaddr/ci/enqueue.py
- openaddr/ci/run_dequeue.py
- openaddr/ci/webapi.py
- openaddr/ci/webhooks.py
- openaddr/ci/worker.py
- openaddr/dotmap.py
- openaddr/run_ec2_ami.py
> Fix SNS Auth

- chef/role-webhooks.json
- openaddr/ci/__init__.py
- openaddr/ci/web.py
- openaddr/ci/webauth.py
Particularly added expected configuration to chef role. Part of #378.
> Stubbed in basic web auth information

- openaddr/ci/templates/oauth-hello.html
- openaddr/ci/templates/oauth-success.html
- openaddr/ci/webauth.py
- openaddr/tests/ci.py
- setup.py
- test.py
Doesn't do much yet, but it's possible to login at `/auth`. Part of #378.
> Add GitHub login flow

- openaddr/ci/__init__.py
- openaddr/ci/webhooks.py
> Switched strings to unicode for non-ASCII paths

- openaddr/ci/objects.py
- openaddr/ci/schema.pgsql
- openaddr/tests/ci.py
Will make it possible to improve [the all CI jobs view](https://results.openaddresses.io/jobs/).
> Added job start and end times to database table

- chef/crontab/recipes/default.rb
Move `openaddr-update-dotmap` and `openaddr-enqueue-sources`.
> Move remaining crontab jobs to chef recipe

- openaddr/ci/__init__.py
- openaddr/ci/work.py
- openaddr/tests/__init__.py
- openaddr/tests/ci.py
> Corrected mistyped S3 key MD5 hash

- openaddr/ci/__init__.py
- openaddr/ci/objects.py
- openaddr/ci/webhooks.py
- openaddr/ci/work.py
- openaddr/ci/worker.py
- openaddr/tests/ci.py
> Fixed some behaviors with missing / old data

- chef/webhooks/recipes/default.rb
- chef/worker/recipes/default.rb
- openaddr/ci/collect.py
- openaddr/ci/work.py
- openaddr/process_one.py
- openaddr/tests/ci.py
Closes #402 and undoes some changes from #401.
> Fixed system encoding to unicode

- openaddr/ci/collect.py
- openaddr/tests/ci.py
> Multipart upload must use raw bytes

- openaddr/ci/webhooks.py
- openaddr/tests/ci.py
To make it possible to determine which secret is being sent from Github.
> Added partial secret output to /hook

- setup.py
It’s been a while since these numbers have moved. Tested each change.
> Upgrade various dependencies

- openaddr/ci/__init__.py
- openaddr/ci/templates/base.html
- openaddr/ci/templates/oauth-hello.html
- openaddr/ci/templates/upload-cache.html
- openaddr/ci/webauth.py
- openaddr/tests/ci.py
Uses OA Github org membership to allow login, upload to subdirectory in S3 bucket. Closes #414.
> Add S3 upload for cache

- openaddr/ci/__init__.py
- openaddr/ci/queuedata.py
Switching from raw dictionaries will make it easier to test future additions to queued data.
> Added wrapper classes for different kinds of queued data

- openaddr/process_one.py
- openaddr/tests/__init__.py
Preview was getting lost along the way.
> Corrected preview file placement in write_state()

- openaddr/cache.py
- openaddr/tests/__init__.py
- openaddr/tests/util.py
- openaddr/util/__init__.py
- setup.py
> Special-cased FTP download in cache.request()

- openaddr/ci/__init__.py
- openaddr/tests/ci.py
> Handling case of missing job.github_comments_url

- openaddr/ci/__init__.py
> Added check for too many status updates

- chef/database/recipes/default.rb
- chef/role-localdev.json
- chef/role-testing.json
- docs/install.md
- test.py
Added a new chef role to make this slightly smoother.
@trescube, I’d love your input on the instructions in `docs/install.md`. Closes #433.
> Document local testing installation process

- openaddr/ci/templates/source.html
- openaddr/ci/webhooks.py
Switched to ISO date format, adds run times, and fixes responsive browser behavior. Follow-on to #448.
> Expand source history view

- openaddr/ci/objects.py
- openaddr/tests/ci.py
Version should have been coming from run state this whole time.
> Using run state to correctly determine code version

- openaddr/ci/objects.py
- openaddr/process_one.py
- openaddr/tests/__init__.py
- openaddr/tests/data/us-tx-runnels-metadata.json
- openaddr/tests/sources/us/tx/runnels.json
Identified missing ESRI tokens in sources. 
Part of #460.
> Categorize ESRI token failure

- openaddr/ci/__init__.py
- openaddr/ci/collect.py
- openaddr/ci/tileindex.py
- openaddr/ci/webapi.py
- openaddr/ci/webauth.py
- openaddr/ci/webcommon.py
- openaddr/ci/webhooks.py
- openaddr/ci/work.py
- openaddr/conform.py
- openaddr/parcels/parse.py
- openaddr/parcels/utils.py
- openaddr/tests/__init__.py
- openaddr/tests/ci.py
- openaddr/util/__init__.py
> Muffle testing logs

- chef/crontab/recipes/default.rb
- openaddr/ci/enqueue.py
- openaddr/dotmap.py
Covers `openaddr-update-dotmap` and `openaddr-enqueue-sources`.
Part of #472.
> Run remaining EC2 tasks under machine-communication role

- openaddr/ci/collect.py
- openaddr/ci/dashboard_stats.py
- openaddr/ci/schema.pgsql
- openaddr/tests/dashboard_stats.py
Added dashboard stats update to `openaddr-collect-extracts`.
> Add stats updates

- chef/role-localdev.json
- docs/install.md
> Update install docs

- openaddr/run_ec2_ami.py
- openaddr/util/__init__.py
Attempts to re-set name if possible, and no longer waits for instances to finish.
Closes #445.
> Fix instance run

- openaddr/ci/webauth.py
- openaddr/tests/ci.py
> Switched to checking public/private org membership on login

- openaddr/ci/templates/base.html
- openaddr/ci/templates/dashboard.html
Make the dashboard page fit into the rest of the site. I'd appreciate careful attention to commit 191b978ea12ae148d37b42fc83ea919faaa61a50; is that an OK thing to do with Jinja2 templates?
> Nelson tweak dashboard

- openaddr/ci/__init__.py
- openaddr/ci/schema.pgsql
- openaddr/render.py
- openaddr/tests/render.py
- Adds names and dates to rendered GeoJSON
- Adds a still-unused `sets.render_geojson` database column
Part of #480.
> Extend rendered GeoJSON

- openaddr/ci/__init__.py
- openaddr/ci/objects.py
- openaddr/ci/webapi.py
- openaddr/ci/webhooks.py
- openaddr/render.py
- openaddr/tests/ci.py
- Added Set.render_geojson property
- Added links to renders and latest set from `/index.json`
Closes #480.
> Complete rendered GeoJSON

- openaddr/ci/templates/runs-table.html
- openaddr/ci/templates/source.html
- openaddr/summarize.py
Add deduced problems in set and source displays. Closes #460.
Example for [Campbell, VA](https://results.openaddresses.io/sources/us/va/campbell):
> Added display of RunState.source_problem values

- openaddr/conform.py
See: https://github.com/openaddresses/openaddresses/pull/2301
> Lowercase "field_to_remove" value in in conform_smash_case

- openaddr/ci/webauth.py
- openaddr/tests/ci.py
> Bumped max cache upload size to 256MB

- openaddr/ci/enqueue.py
> Increase enqueue autoscale interval to 8 hours

- openaddr/ci/collect.py
- openaddr/ci/schema.pgsql
- openaddr/ci/templates/index.html
- openaddr/tests/ci.py
Followup to https://github.com/openaddresses/machine/issues/519.
> Add North America, non-U.S. extract

- chef/role-worker.json
- chef/tippecanoe/recipes/default.rb
Bumps Tippecanoe to 1.15.1 and adds it to Worker role. First step of #466.
> Upgrade Tippecanoe

- openaddr/cache.py
- openaddr/ci/collect.py
- Closes #528.
- Finishes item left off of #525.
> Two small fixes

- openaddr/jobs.py
> Extended job timeout to 12 hours

- chef/webhooks/recipes/default.rb
- chef/worker/recipes/default.rb
- openaddr/ci/__init__.py
- openaddr/ci/webhooks.py
- openaddr/tests/ci.py
> Added REJECT_NEW_JOBS feature flag

- lambda.py
- openaddr/util/templates/task-instance-userdata.sh
Better comments, less repetition, and some tests.
> Cleaned up Lambda SNS function

- setup.py
This wants to be kept up-to-date so that awscli works.
> Bumped boto3 version to 1.4.4

- openaddr/ci/objects.py
- openaddr/conform.py
- openaddr/process_one.py
- openaddr/tests/__init__.py
- openaddr/tests/ci.py
- openaddr/tests/conform.py
- openaddr/tests/sources/cz-countrywide-bad-tests.json
- openaddr/tests/sources/cz-countrywide-disabled-tests.json
- openaddr/tests/sources/cz-countrywide-good-tests.json
- openaddr/tests/sources/cz-countrywide-implied-tests.json
- openaddr/tests/sources/cz-countrywide-no-tests.json
- test.py
> Support new in-source tests

- chef/data/local.json
- chef/webhooks/recipes/default.rb
- openaddr/ci/__init__.py
> Add slippymap preview URL to status comments

- openaddr/render.py
- openaddr/tests/ci.py
- openaddr/tests/render.py
> Added address count to rendered GeoJSON output

- openaddr/ci/__init__.py
- openaddr/ci/objects.py
- openaddr/ci/templates/index.html
- openaddr/ci/webapi.py
- openaddr/ci/webhooks.py
- openaddr/tests/ci.py
Will look like this:
> This is a summary view of OpenAddresses data. 406,899,730 addresses have been processed as of Tuesday, Mar 07, 2017. Out of 1,965 sources, 1,895 have completed.
Closes #571.
> Update top paragraph with sources count

- openaddr/ci/webhooks.py
> Accepting either "state" or "output" in webhooks.app_get_job()

- openaddr/ci/__init__.py
- openaddr/ci/objects.py
- openaddr/ci/queuedata.py
- openaddr/tests/ci.py
Switched to using RunState instances everywhere and converting to/from dictionaries on every database boundary. Finished work started in #572, prepares for #567.
> Complete RunState usage

- openaddr/ci/objects.py
- openaddr/ci/templates/job.html
- openaddr/ci/webhooks.py
Follows on to #575 after #576.
> Got rid of this prior hack

- chef/crontab/recipes/default.rb
- openaddr/ci/coverage/calculate.py
Every three days; closes #581.
> Update population coverage page on a regular cycle

- openaddr/ci/templates/coverage.html
- openaddr/ci/webcoverage.py
Saw some errors indicating the the nice_integer filter in coverage was stomping on the other one.
> Fixed naming conflict with Jinja nice_integer filter

- openaddr/ci/templates/dashboard.html
Also tweaks graph ranges.
Closes #597.
> Link dashboard sources

- openaddr/ci/__init__.py
- openaddr/ci/collect.py
- openaddr/ci/coverage/calculate.py
- openaddr/ci/enqueue.py
- openaddr/ci/run_dequeue.py
- openaddr/ci/sum_up.py
- openaddr/ci/tileindex.py
- openaddr/ci/webapi.py
- openaddr/ci/webauth.py
- openaddr/ci/webcoverage.py
- openaddr/ci/webhooks.py
- openaddr/ci/worker.py
- openaddr/dotmap.py
- openaddr/preview.py
- openaddr/run_ec2_ami.py
- openaddr/slippymap.py
Currently log to group `testing-logs`. Also remove gratuitous AWS key/secret arguments. Part of #608.
> Add Cloudwatch logging

- openaddr/dotmap.py
> Added number, street, and unit to dotmap properties

- openaddr/ci/templates/dashboard.html
> Added time units to chart titles

- openaddr/ci/webhooks.py
Failed sample data requests sometimes surface transient S3 or HTTP errors that can be annoying in logs and Slack alerts, so add some retries.
> Added retries to webhooks.app_get_run_sample()

- openaddr/ci/templates/source.html
> Fixed source page title

- openaddr/ci/webhooks.py
> Suppressed annoying errors in webhooks.app_get_sets()

- .circleci/config.yml
- .circleci/prepare-docker-images.sh
- ops/update-scheduled-tasks.py
- ops/update-webhooks-group.py
Add Deploy step to Circle CI configuration so previously-manual deploy step happens automatically.
> Deploy continuously

- openaddr/ci/objects.py
> Add timing logging to ci.objects.read_completed_runs_to_date()

- openaddr/ci/objects.py
- openaddr/ci/webcommon.py
- openaddr/ci/webhooks.py
> Start monitoring home page load time

- openaddr/tests/ci.py
> Added test for objects.read_completed_runs_to_date_cheaply()

- openaddr/ci/web.py
- openaddr/ci/webauth.py
- openaddr/tests/ci.py
- setup.py
... as long as `ProxyFix` is configured correctly 😄
> url_for does the work of callback_url

- openaddr/ci/webhooks.py
Fetch sample HTML through the CDN.
> Use nice_domain for sample.html

- openaddr/ci/web.py
Used the debug /headers endpoint to get new values for the `ProxyFix` middleware.
> Update proxy fix again

- Dockerfile-prereqs
See conversation at https://twitter.com/enf/status/1184318325439860738
> Update tippecanoe version in docker image

- openaddr/cache.py
- openaddr/conform.py
- openaddr/tests/cache.py
This is a newer copy of https://github.com/openaddresses/machine/pull/656
> Support chain function in field_names_to_request

- openaddr/conform.py
- openaddr/tests/conform.py
Unfortunately fxn values are not arrays.
> Fixed get method

- openaddr/conform.py
- openaddr/parcels/utils.py
- openaddr/tests/conform.py
- openaddr/tests/parcels.py
For https://github.com/openaddresses/machine/issues/766
> Fix get array function tests

- openaddr/conform.py
again... have problems with running unit test locally and don't know how to run CI before merge
> Fixed get array from string code

- openaddr/ci/objects.py
- openaddr/tests/ci.py
> Revert the slow query change

- openaddr/process_one.py
I noticed that sources have been failing in the existing machine setup for several months now because the process-one code isn't reading the v2 source schema properly. This fixes that.
> Fix process-one to support v2 sources

- openaddr/ci/__init__.py
Machine tasks are failing pretty frequently because CloudWatch is throttling us and then we're not getting the next sequence token properly. This attempts to solve that. Heavily influenced by [this code](https://github.com/lincheney/journald-2-cloudwatch/blob/master/main.py#L264) in another CloudWatch logging implementation.
> Handle invalid sequence token response from cloudwatch
